name: PullRequest Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir "poetry==1.8.2"
          poetry install
      - name: Execute Tests
        run: poetry run pytest
